---
abstract: 'per-request file-based logging engine for Dancer'
author:
  - 'Fayland Lam <fayland@gmail.com>'
build_requires:
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.5, Dist::Zilla version 5.014, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Logger-File-PerRequest
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Dancer: 1.3113
  Scalar::Util: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/fayland/perl-Dancer-Logger-File-PerRequest/issues
  homepage: https://github.com/fayland/perl-Dancer-Logger-File-PerRequest
  repository: https://github.com/fayland/perl-Dancer-Logger-File-PerRequest.git
version: 0.02
